### ISSUE TITLE
HARDWARE circuit_diagram/Rostock301/

### ISSUE THREAD

**Issue by kaktusus** [Geeetech3D/Smartto-Eclipse#11]
Due to a design error with regard to the comparator, I suggest not to mount the following parts:
JP1
Q4, Q1, IC5
And the related passive elements.

It is often the case that an accidental short-circuit of the fan leads to damage to the mosfet transistor (Q4). This one gets punctures and supplies the fans with 24V DC supply voltage.
Also applies to a board built on µC AVR.
I had such a case myself, and I read about similar things in the forum.

Kind regards.
kaktus

**Comment by Geeetech3D** [comment]
@kaktusus  that's good for us,because we are redesigning this hardware.

**Comment by kaktusus** [comment]
I would be happy to take part in the design of a new controller.
