### ISSUE TITLE
Request: change naming of firmware files

### ISSUE THREAD

**Issue by thatjoshguy** [Geeetech3D/Smartto-Eclipse#20]
Currently the firmware for the A30 is distributed in two files, an "S" and and "M" file.  One is for the screen, and one is for the main board... 

For English speaking users one would assume the "S" file is for the Screen, and the "M" file is for the Main board... but this is not the case!  The "M" file is for the screen, and vice versa.

When distributing future firmware releases, could they contain the words "SCREEN" and "MAIN" in their file names so there is no confusion?

**Comment by Geeetech3D** [comment]
A reasonable request. At the beginning, we set 'M' for Master device and 'S' for Slave device. But it seems that making users confused. We're going to make an internal discussion about it.

**Comment by kaktusus** [comment]
Each description is good provided it is explained in the readme file, which is located in the main branch of the project.

**Comment by thatjoshguy** [comment]
Master and Slave does make sense in that context. If it was noted in the readme that would be good.
