### ISSUE TITLE
Lack of documentation (Step-by-Step) on how to compile the Firmware

### ISSUE THREAD

**Issue by redangel1984** [Geeetech3D/Smartto-Eclipse#22]
It is good that the firmware is open source and that we can see and modify the source(values) etc.
but there is no **detailed documentation** on how to compile the firmware and how to get the two "*.bin" files to use it with the Upgrade_Tool.

A detailed step-by-step instruction is needed with all the Steps from Installing the Workspace tools (Eclipse and/or IAR) to the Uploading of the firmware (separate PDF or Video Tutorial would be great)

There are a bunch of tutorials for Marlin and Arduino. but these two tools( Eclipse and IAR) are new tools and there isn't any documentation on the internet. 
FAQ:
Are the Compiling programs Free? I found the only option on the website for IAR Embeded Workbench to buy it.
Are there macOS version for the Workbenches(Eclipse or IAR) available?
There is already mentioned by Issue #21, what is the difference between the two Projects IAR and Eclipse, and why are there two? which is the actual Stable Version ?

I don't wonder why the development is so slow and so little contribution.
There is so much confusion and lack of documentations on the Firmware.

**Comment by Geeetech3D** [comment]
Sorry for making you confused. we will add detailed documentation about compilation later today.

Q1: How to get two bin files to use it with upgrade tool?
A1: You can find all firmwares which have been compiled in geeetech.com/firmware. You can upgrade the machine with Easyprint 1.2.3 or Firmware tool V1.0.(earlier version had some bugs in upgrading but now fixed)

Q2: IAR Free?
A2: No

Q3: Are there macOS version for the Workbenches(Eclipse or IAR) available?
A3: Yes for Eclipse and no for IAR, but you can install your own virtual machine.

Q4: which is the actual Stable Version?
A4: IAR. you can find the answer in README

Thanks for your attention.
