### ISSUE TITLE
X & Y Axis movment read out

### ISSUE THREAD

**Issue by Suggy50** [Geeetech3D/Smartto-Eclipse#6]
When moving X & Y axis the screen only goes to 150mm but they travel all the way.

**Comment by crncrussell** [comment]
I have this same problem.

**Comment by Geeetech3D** [comment]
Thanks for report this bug,we have fixed this bug, and will release the new version next month after testing

**Comment by redangel1984** [comment]
I have the same issue. My question is, how can I reupload/upgrade Firmware if I am using a Mac Computer, is it even possible. I have no acces to Windows Computer but I would like to Upgrade the FW.

**Comment by Suggy50** [comment]
I have the latest firmware and now it only read upto 90

**Comment by Suggy50** [comment]
This issue is now fixed

**Comment by thatjoshguy** [comment]
@Suggy50 - was the issue corrected in the latest firmware, or did you do something else to correct it?
