### ISSUE TITLE
Bed temps

### ISSUE THREAD

**Issue by Suggy50** [Geeetech3D/Smartto-Eclipse#7]
Bed temp is way off 
 50 is actually 40
 100 is 68
 108 is 69

**Comment by Geeetech3D** [comment]
@Suggy50  what is the temperature in the room?

**Comment by Suggy50** [comment]
Sorry for late reply 
This time off the year inbetween10 and 40 degress

**Comment by thatjoshguy** [comment]
This would most likely indicate an issue with the hardware, not a firmware issue.  My Geetech A30 does not appear to have this issue.
