### ISSUE TITLE
Not a issue, a request for a new feature, Set step/mm from display

### ISSUE THREAD

**Issue by marcofanuntza** [Geeetech3D/Smartto-Eclipse#9]
Hello, this post is not for a issue problem, is a request for a new function, could be very nice  set the steps-per-unit for one or more axes directly from display, like Marlin Firmware do.....

i have a Geeetech A30, thanks!

**Comment by Geeetech3D** [comment]
Hi marcofanuntza, thanks for your good sugesstion! we will add more settings on the smartto_motor_tool.exe, not in A30 display now because of that it will be complicated for some beginners

**Comment by thatjoshguy** [comment]
Using the tool requires a Windows PC, and definately not easy for beginners. These settings as well as jerk and acceleration, max speed, etc.  need to be configurable on the touch screen without the need for a PC.
